server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index frontend/login.html;

    # Redireciona / para /frontend/login.html (entry point)
    location = / {
        return 302 /frontend/login.html;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
